
import java.util.HashSet;
import java.util.Set;
import Clases.Directorio;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author arceb
 */
public class JframeNuevo extends javax.swing.JFrame {

    /**
     * Creates new form JframeNuevo
     */
    
    public static Set<String> ciudades = new HashSet<>();
    
    public JframeNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCliente = new javax.swing.JMenu();
        ItemAgregarCliente = new javax.swing.JMenuItem();
        ItemBuscarCliente = new javax.swing.JMenuItem();
        ItemBorrarCliente = new javax.swing.JMenuItem();
        jMenuDirectorio = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuCiudad = new javax.swing.JMenu();
        ItemAgregarCiudad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDEscritorioLayout = new javax.swing.GroupLayout(jDEscritorio);
        jDEscritorio.setLayout(jDEscritorioLayout);
        jDEscritorioLayout.setHorizontalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        jDEscritorioLayout.setVerticalGroup(
            jDEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jMenuCliente.setText("Cliente");

        ItemAgregarCliente.setText("AgregarCliente");
        ItemAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(ItemAgregarCliente);

        ItemBuscarCliente.setText("BuscarCliente");
        ItemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(ItemBuscarCliente);

        ItemBorrarCliente.setText("BorrarCliente");
        jMenuCliente.add(ItemBorrarCliente);

        jMenuBar1.add(jMenuCliente);

        jMenuDirectorio.setText("Directorio");

        jMenuItem2.setText("Buscar clientes por ciudad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuDirectorio.add(jMenuItem2);

        jMenuBar1.add(jMenuDirectorio);

        jMenuCiudad.setText("Ciudad");

        ItemAgregarCiudad.setText("Agregar Ciudad");
        ItemAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarCiudadActionPerformed(evt);
            }
        });
        jMenuCiudad.add(ItemAgregarCiudad);

        jMenuBar1.add(jMenuCiudad);

        jMenu4.setText("Salir");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDEscritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarClienteActionPerformed
        // TODO add your handling code here:
        
        AgregarContacto agregar = new AgregarContacto();
        agregar.setSize(450, 470);
        agregar.setVisible(true);
        jDEscritorio.add(agregar);
        
        
    }//GEN-LAST:event_ItemAgregarClienteActionPerformed

    private void ItemAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarCiudadActionPerformed
        
        AgregarCiudad agregar = new AgregarCiudad();
        agregar.setSize(450,350);
        agregar.setVisible(true);
        jDEscritorio.add(agregar);
        
    }//GEN-LAST:event_ItemAgregarCiudadActionPerformed

    private void ItemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarClienteActionPerformed
        BuscarCliente buscar = new BuscarCliente();
        buscar.setSize(450, 470);
        buscar.setVisible(true);
        jDEscritorio.add(buscar);
    }//GEN-LAST:event_ItemBuscarClienteActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        BuscarClientesCiudad ciudad = new BuscarClientesCiudad();
        ciudad.setSize(650, 350);
        ciudad.setVisible(true);
        jDEscritorio.add(ciudad);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAgregarCiudad;
    private javax.swing.JMenuItem ItemAgregarCliente;
    private javax.swing.JMenuItem ItemBorrarCliente;
    private javax.swing.JMenuItem ItemBuscarCliente;
    private javax.swing.JDesktopPane jDEscritorio;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCiudad;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuDirectorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
